VERY_HIGH_MATCH_COUNT = 1000000
DECLINE_TO_IDENTIFY = "ai skip"
FR_ACCEPTANCE_PARAMETER = 0.15
VGG_ACCEPTANCE_PARAMETER = 0.15
COURTESY_ACCEPTANCE_PARAMETER = 0.05
STRICT_ACCEPTANCE_PARAMETER = 0.20
TEMP_FRAME_DATA_PATH = "/content/drive/MyDrive/AI VFX Assistant/temp_frame_data"
FRAME_CONTROL = 2
TEMP_IMG_STORAGE_PATH = "/content/drive/MyDrive/AI VFX Assistant/temp_img_data"
FR_DATASET_PATH = "drive/MyDrive/AI VFX Assistant/dataset"
FR_DETECTION_METHOD = "hog"
FR_ENCODINGS_DUMP_PATH = "/content/drive/MyDrive/AI VFX Assistant/fr_encodings.pickle"
ALGO_MODELS = ["VGG-Face", "Facenet", "Facenet512", "OpenFace", "DeepFace", "DeepID", "ArcFace", "Dlib", "SFace"]
VGG_FACE_MODEL = "VGG-Face"
FACENET_MODEL = "Facenet"
VGG_DATASET_PATH = "drive/MyDrive/AI VFX Assistant/dataset"